namespace FitStore.Web.Infrastructure
{
    using Common.Extensions;
    using Data.Models;
    using System;
    using System.Collections.Generic;

    public class SeedConstants
    {
        private static DateTime bestBeforeDate = DateTime.UtcNow.AddYears(1);
        private static DateTime date = DateTime.UtcNow;

        public const string Protein = "Protein";
        public const string AminoAcids = "Amino Acids";
        public const string Creatine = "Creatine";
        public const string Vitamins = "Vitamins";

        public const string Whey = "Whey";
        public const string Gainer = "Gainer";
        public const string Isolate = "Isolate";
        public const string Bcaa = "BCAA";
        public const string Glutamine = "Glutamine";
        public const string PreWorkouts = "Pre Workouts";
        public const string Monohydrate = "Monohydrate";
        public const string Matrix = "Matrix";
        public const string Multivitamins = "Multivitamins";
        public const string FishOil = "Fish Oil";

        public const int WheyId = 1;
        public const int GainerId = 2;
        public const int IsolateId = 3;
        public const int BcaaId = 4;
        public const int GlutamineId = 5;
        public const int PreWorkoutsId = 6;
        public const int MonohydrateId = 7;
        public const int MatrixId = 8;
        public const int MultivitaminsId = 9;
        public const int FishOilId = 10;

        public const string OptimumNutrition = "Optimum Nutrition";
        public const string ControlledLabs = "Controlled Labs";
        public const string MusclePharm = "Muscle Pharm";
        public const string BulkPowders = "Bulk Powders";
        public const string Gaspari = "Gaspari";
        public const string Bsn = "BSN";

        public const int OptimumNutritionId = 1;
        public const int ControlledLabsId = 2;
        public const int MusclePharmId = 3;
        public const int BulkPowdersId = 4;
        public const int GaspariId = 5;
        public const int BsnId = 6;

        public const string OptimumNutritionAddress = "USA, Florida, Miami";
        public const string ControlledLabsAddress = "USA, Texas, Houston";
        public const string MusclePharmAddress = "USA, California, Los Angeles";
        public const string BulkPowdersAddress = "USA, Caifornia, San Francisko";
        public const string GaspariAddress = "USA, Colorado, Denver";
        public const string BsnAddress = "USA, Nevada, Las vegas";

        public static IEnumerable<Supplement> proteinSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/gold-standard-100%-whey.jpg".ToByteArray(), SubcategoryId = WheyId, ManufacturerId = OptimumNutritionId, Name = "Gold Standard 100% Whey", Description ="True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 8, Price = 99.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/myofusion-advanced.jpg".ToByteArray(), SubcategoryId = WheyId, ManufacturerId = GaspariId, Name = "MyoFusion Advanced", Description = "Myofusion Advanced Protein’s formula provides the most up to date and scientifically proven blend of protein available. Featuring a synergistic mix of immediate, fast acting, and time released forms of whey & casein, Myofusion is able to provide the body with muscle fortifying amino acids all day long. Available in delicious flavors like Peanut Butter Cookie, Cookies & Cream, and creamy Milk Chocolate, Myofusion is the perfect solution for any athlete looking to improve their performance and physique!", Quantity = 10, Price = 44.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/combat-100%-whey.jpg".ToByteArray(), SubcategoryId = WheyId, ManufacturerId = MusclePharmId, Name = "Combat 100% Whey", Description = "Combat 100% WHEY is a low-carb, high-protein, great-tasting protein supplement with minimal fat and low sodium that delivers fast digesting protein sources to build and maintain lean muscle mass. Combat 100% Whey combines two of the fastest digesting, most efficient, and cleanest protein sources available: Whey Protein Isolate and Whey protein Concentrate. Whey protein has the highest bioavailability among complete proteins (protein that contains a complete amino acid profile of all 9 essential amino acids) and also has the highest absorption rate among any other proteins.", Quantity = 0, Price = 54.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/syntha-6.jpg".ToByteArray(), SubcategoryId = GainerId, ManufacturerId = BsnId, Name = "Syntha 6", Description = "Syntha 6 is an ultra-premium protein powder with 22g protein per serving and is BSN's best-tasting protein on the market. Syntha 6 not only includes essential amino acids and essential fatty acids, but is also an excellent source of fiber, which makes it a nutritious and multi-functional protein supplement. Syntha 6 is the go-to protein for any nutrition or exercise regimen because it is designed to suit a variety of active lifestyles and diet plans. And with Syntha 6, the high standard of quality protein comes with taste to match, thanks to BSN's exclusive flavor technology.", Quantity = 6, Price = 89.99m},
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/complete-mass.jpg".ToByteArray(), SubcategoryId = GainerId, ManufacturerId = BulkPowdersId, Name = "Complete Mass", Description = "Complete Mass is a calorie dense weight gainer, designed for real hard gainers. Not only does Complete Mass contain over 500kcal per serving, but it is crammed with multiple sources of protein and is fortified with amino acids such as leucine. In addition, Complete Mass tastes so good that you'll look forward to each and every shake.", Quantity = 0, Price = 64.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/gold-standard-100%-isolate.jpg".ToByteArray(), SubcategoryId = IsolateId, ManufacturerId = OptimumNutritionId, Name = "Gold Standard 100% Isolate", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 4, Price = 74.99m},
        };

        public static IEnumerable<Supplement> aminoAcidsSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/no-xplode.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = BsnId, Name = "N.O. Xplode", Description = "N.O.Xplode is a pre-training igniter designed for athletes of all levels to help maximize workout performance. To achieve the most effective training session, both mental and physical energy are a must. Focus is then needed to harness this energy and drive a strong mind-muscle connection. This mind-muscle connection will help you achieve a greater workout intensity, enhanced strength, and will help you push your body past previous limits. A complete pre workout supplement should support all of these benefits. N.O.Xplode was designed with advanced ingredient technology to help deliver increased energy and endurance, support mental focus and muscular strength, and provide second-to-none intensity and performance.", Quantity = 8, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/bcaa-6000.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = GaspariId, Name = "BCAA 6000", Description = "BCAA 6000 from Gaspari Nutrition uses a leucine heavy, 4:1:1 ratio of 100% pure branched chain amino acids in a formula that provides clinically validated and effective quantities of these critical nutrients in every dose. The addition of an advanced, highly bio-available form of Vitamin B-6 to the BCAA 6000 complex, will also help to enhance your energy and endurance levels, helping to further maximize your training while simultaneously enhancing recovery.", Quantity = 4, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/purple-wrath.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = ControlledLabsId, Name = "Purple Wraath", Description = "The Purple Wraath PurplEAA Complex is a very efficient formula based on the science of actual homo sapiens muscle protein and clinical studies on human amino acid assimilation. Essential Amino Acids (EAA's) are the building blocks of lean muscle mass, but the EAA's from whey protein can take hours to enter circulation.", Quantity = 6, Price = 54.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/bcaa-1000.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = OptimumNutritionId, Name = "BCAA 1000", Description = "BCAA 1000 contains a balance of Branched Chain Amino Acids, which are building blocks of muscle mass and size. Metabolized directly in the muscle, BCAAs may improve nitrogen retention by sparing other amino acid groups for repair and rebuilding. The Branched Chain Amino Acids (BCAAs), so named because of their unique branched chemical structure, are essential in that the body cannot make them from other compounds. In recent times, these amino acids have been investigated for their potential anticatabolic (reducing muscle breakdown) and anabolic (muscle building) effects.", Quantity = 2, Price = 14.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/glutamine-powder.jpg".ToByteArray(), SubcategoryId = GlutamineId, ManufacturerId = OptimumNutritionId, Name = "Glutamine Powder", Description = "Glutamine is the most abundant amino acid in the body, comprising more than 60% of the free amino acid pool in skeletal muscle and greater than 20% of total circulating amino acids. Supplemental L-Glutamine may help reduce muscle soreness and rebuild muscle tissue.", Quantity = 4, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/pure-l-glutamine.jpg".ToByteArray(), SubcategoryId = GlutamineId, ManufacturerId = GaspariId, Name = "Pure L-Glutamine", Description = "Utilizing only ultra-pure L-Glutamine with no synthetic colors or fillers, Gaspari Nutrition's glutamine is your solution in amino acid support. Whether you are strength training or pushing yourself through long aerobic training sessions, glutamine can help support one of your body's most abundant amino acids. Gaspari Nutrition's L-Glutamine offers you a high value product at a rock bottom price. You can rest assured this product is made with only the highest quality in mind. Be sure when taking glutamine to drink at least 8 glasses of water daily for optimal results in strength and conditioning training.", Quantity = 4, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/cell-mass-2.0.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = BsnId, Name = "Cell Mass 2.0", Description = "CellMass 2.0 is a concentrated post-workout recovery agent that helps promote recovery, endurance, strength and overall performance. When taken as directed, CellMass 2.0's formula delivers 5g of creatine, 3g of glutamine and glutamic acid, and 10g of amino acids per day, along with taurine and hydrolyzed whey protein, all designed to help kick-start the recovery process after a workout.", Quantity = 6, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/super-pump-max.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = GaspariId, Name = "Super Pump MAX", Description = "Are you ready to take your workouts to the MAX? If so, the only way to get there is through the use of clinically researched and validated ingredients at their proven doses. Super Pump MAX is a one of a kind breakthrough in pre-workout supplementation that offers the most effective compounds available for intense energy and focus, mind blowing pumps, and muscle anabolism.", Quantity = 6, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/white-flood.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = ControlledLabsId, Name = "White Flood", Description = "Now called White Flood Classic, it is a tried and true preworkout formula that will rev you up for lifting and cardio like none other. Not only will you experience out of this world pumps, but tons of extra energy and true muscle building potential. That muscle building potential comes from the addition of compounds usually not seen in preworkout formulas of the past. We have also included anti-oxidants to scavenge any free radicals normally elicited by Nitric Oxide inducing ingredients during exercise.", Quantity = 6, Price = 29.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/natural-series-pre-workout.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = MusclePharmId, Name = "Natural Series Pre-Workout", Description = "Muscle Pharm Pre-Workout is a combination of organic caffeine, natural botanicals, electrolytes, and amino acids that work together to support your training goals and bring you pure, unadulterated results. We brought together a team of athletes, scientists and naturalists who believe that an authentic, results-focused supplement can also be clean, pure and nutritive.", Quantity = 0, Price = 39.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/gold-standard-pre-workout.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = OptimumNutritionId, Name = "Gold Standard Pre-Workout", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 4, Price = 29.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/bcaa-3-1-2.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = MusclePharmId, Name = "BCAA 3:1:2", Description = "With Muscle Pharm's BCAA 3:1:2, you get a patent-pending branched chain amino acid complex that not only delivers when it counts but gives you precisely what your body needs. With the ideal mix of l-leucine (3 grams per serving), l-valine (2 grams) and l-isoleucine (1 gram), you're getting all the vast benefits of BCAAs before and after a workout. It's the perfect combination of BCAAs to reduce muscle breakdown, fuel muscle development, and support an increase in lean body mass. There is nothing subpar about MP's BCAA 3:1:2 and your results will be proof of that. This BCAA complex is pure and all about performance.", Quantity = 6, Price = 19.99m },
        };

        public static IEnumerable<Supplement> creatineSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/green-magnitude.jpg".ToByteArray(), SubcategoryId = MatrixId, ManufacturerId = ControlledLabsId, Name = "Green Magnitude", Description = "We have responded to customer demand and the result: Green MAGnitude... Creatine with attitude. If you want to increase your stamina in the gym and gain size and strength, Green MAGnitude is the right choice for you. If you want similar results in convenient capsule form, we recommend Green Bulge. Either way, you are getting a full dose of patented Magnesium Creatine Chelate that has been clinically surmised to increase strength. Green MAGnitude is our most advanced powder creatine matrix and one of the first creatine products on the market to combine Magnesium Creatine Chelate (a patented form of creatine), with Dicreatine Malate (creatine bound with Malic Acid) to deliver synergistic benefits you can actually feel working during your workout.", Quantity = 8, Price = 39.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/green-bulge.jpg".ToByteArray(), SubcategoryId = MatrixId, ManufacturerId = ControlledLabsId, Name = "Green Bulge", Description = "Green Bulge one is one of our most advanced creatine matrix volumizers. It combines Magnesium Creatine Chelate (MCC), a patented form of creatine, with Dicreatine Malate (2CM) to deliver synergistic benefits. Controlled Labs has responded to customer demand and the result: Green BULGE new and improved, delivering a synergistic formula you can actually feel working during your workouts. The exclusive stimulant-free HyperBULGE complex features Curcuminoids, GYMnemic Acid, and more boosting performance while taking muscle recovery / regeneration to the next level. The HyperCRE complex features a potent combination of patented Magnesium Creatine Chelate and 2CM (Dicreatine Malate), beneficial during both anaerobic and aerobic workouts. Featuring clinically surmised active ingredients and potent B Vitamins.", Quantity = 8, Price = 39.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/micronized-creatine-powder.jpg".ToByteArray(), SubcategoryId = MonohydrateId, ManufacturerId = OptimumNutritionId, Name = "Micronized Creatine Powder", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 0, Price = 19.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/qualitine.jpg".ToByteArray(), SubcategoryId = MonohydrateId, ManufacturerId = GaspariId, Name = "Qualitine", Description = "Gaspari Nutrition features Qualitin, a premium brand of creatine guaranteed to be the highest in quality, purity and safety. Gaspari Nutrition uses only 99.9% pure creatine monohydrate that has been micronized to insure instant dissolution into water and other suitable liquids. Qualitine is tasteless, odorless, crystalline and pure-qualities that are obvious from the moment you open the bottle and every time you use this elite product. Creatine monohydrate is perhaps the most studied dietary supplement in the Sports Nutrition industry.", Quantity = 4, Price = 14.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/bulk-powders-creatine.jpg".ToByteArray(), SubcategoryId = MonohydrateId, ManufacturerId = BulkPowdersId, Name = "Bulk Powders Creatine", Description = "Bulk Powders Creatine Monohydrate is a high quality, ultra-pure form of Creatine Monohydrate. Not only this, but Bulk Powders Creatine Monohydrate offers incredible value for money. Many Creatine Monohydrate products have been shown to contain up to 5% impurities, whereas Bulk Powders Creatine Monohydrate is 99.9% pure. We display the latest Certificate of Analysis on this page(under the product image) as evidence of our commitment to product quality.", Quantity = 0, Price = 24.99m },
        };

        public static IEnumerable<Supplement> vitaminsSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/omega-3-fish-oil.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = BulkPowdersId, Name = "Omega 3 Fish Oil", Description = "Bulk Powders Omega 3 Fish Oil Softgels contains 180mg EPA and 120mg DHA per softgel – this is far higher than many fish oil products. If you’re looking for even higher levels of EPA and DHA, then take a look at our popular Super Strength Fish Oils 1000mg. Omega 3 Fish Oil Softgels deliver EPA and DHA in a cost effective format.", Quantity = 6, Price = 4.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/fish-oil-softgels.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = OptimumNutritionId, Name = "Fish Oil Softgels", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 2, Price = 9.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/orange-oximega-fish-oil.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = ControlledLabsId, Name = "Orange OxiMega Fish Oil", Description = "Many people don’t realize the crucial effects that overall health supplements can play on their training. Without the essential nutrients your body needs to survive and flourish, it cannot build a strong foundation that is so crucial to lean mass gains. Orange OxiMega was designed to help you establish a strong, healthful, foundation on which to base your training, diet and supplementation. Coupled together with Orange Triad, Super Fish Oil Formulas will have all of your overall health requirements exceeded including omegas, vitamins, minerals, fruit, vegetables, digestive support, immune support, joint support, and cardiovascular support.", Quantity = 8, Price = 19.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/muscle-pharm-fish-oil.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = MusclePharmId, Name = "Fish Oil Muscle Pharm", Description = "This essential fatty acid facilitates an overall decrease in fat and cholesterol consumption from your omega intake. Not only are these Nordic fish oil softgels a nutritional masterpiece, they are also enteric coated and citrus flavored so you won't experience the regurgitation (which are called fish oil burps) that people associate with cheaper, cruder formulations. Our Nordic fish oil's molecular integrity is protected so you can be assured of the utmost quality.", Quantity = 4, Price = 14.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/opti-men.jpg".ToByteArray(), SubcategoryId = MultivitaminsId, ManufacturerId = OptimumNutritionId, Name = "Opti-Men", Description = "Optimum Nutrition's Opti-Men is a complete Nutrient Optimization System providing 70+ active ingredients in 4 blends specifically designed to support the nutrient needs of active men. Taken as a single tablet at breakfast, lunch and dinner, our new & improved multi provides 22 vitamins and essential minerals - including 1,500 IU of Vitamin D, free form amino acids, botanical extracts and antioxidants in foundational amounts that can be built upon through consumption of a healthy balanced diet. Think of Opti-Men as potent nutritional insurance for your fitness lifestyle.", Quantity = 8, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/opti-women.jpg".ToByteArray(), SubcategoryId = MultivitaminsId, ManufacturerId = OptimumNutritionId, Name = "Opti-Women", Description = "Vitamins, minerals and other essential nutrients are the body's fundamental building blocks. Among other things, they contribute to our energy levels, immunity, performance and overall vitality. Opti-Women has been designed as a comprehensive Nutrient Optimization System complete with botanicals, antioxidants, and other gender-focused components. By packing 40 active ingredients into one pill, much more than a multi has been created.", Quantity = 8, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/orange-triad.jpg".ToByteArray(), SubcategoryId = MultivitaminsId, ManufacturerId = ControlledLabsId, Name = "Orange Triad", Description = "Designed for the serious athlete, Orange Triad delivers! Serious athletes are unique in that they intentionally subject their bodies to incredible amounts of stress with training and cardio. Over time, muscles, tendons, and ligaments take longer to recover which means you can't train them as often as you would like. Nutritional support is key to getting optimal results from your training. Orange Triad combines key vitamins, minerals, and nutrients for supporting optimal digestion, immune system, and joint health into one twice daily dietary supplement. The Joint and Flex Complexes help lubricate joints and cartilage as well as increase the resiliency of connective tissue, while the Digestion and Immune Complex includes digestive aids, and nutrient partitioning agents to take your performance to the next level.", Quantity = 10, Price = 29.99m }
        };

        public static IEnumerable<Review> reviewsFirstPart = new List<Review>
        {
            new Review { SupplementId = 25, Rating = 10, PublishDate = date.AddDays(-15), Content = "This is my first to purchase supplements and my first time to purchase on bodybuilding.com. I would like to say I feel very satisfied whether for the service or products. The taste is very great, I got the discount that buy 1 get 1 50% off, so I got two flavors which are strawberry milkshake and chocolate milkshake. I hope someday this product could be developed to lower carbs and lower fat. But anything else is perfect. I tried to mixed the chocolate flavor powder and water and raw oats as my breakfast it is not very good; then I tried the strawberry flavor with the oats, it is awesome, maybe because the strawberry one is a little sweeter than the chocolate one. Pretty good products, I would like to recommend to my friends who would like to buy protein powder!" },
            new Review { SupplementId = 23, Rating = 9, PublishDate = date.AddDays(-30), Content = "One of my favourite proteins, second only to Vega Sport Vanilla in flavour, however looking at price this comes out on top. I generally mix my protein with about 1 1/2 cup of 2% milk. I had high hopes for Mocha Cappuccino, however I was let down. Just not what I was expecting, not a strong flavour at all. French Vanilla Creme is absolutely amazing mixed with a half cup of frozen mixed berries and milk. Chocolate Peanut Butter was also really good, both on its own and blended with some frozen coffee ice cubes. Delicious Strawberry tastes pretty much like a cheaper strawberry milkshake, it is a fake strawberry taste, but one of the better ones."  },
            new Review { SupplementId = 27, Rating = 9, PublishDate = date.AddDays(-45), Content = "I was lucky enough to get a tub of this off a promo and I was super excited to try out Chocolate Hazelnut Creme. The profile on this is definitely impressive as is with all of Gaspari's line. The big thing for me especially in protein powders is taste as I'm sure most are, this stuff is off the charts whether in milk or water it's all delicious. Definitely going to be trying out more flavors in the future. Don't hesitate to give this a try, great taste, profile and affordable for the quality." },
            new Review { SupplementId = 26, Rating = 9, PublishDate = date.AddDays(-60), Content = "This is my go to whey protein! The macros are amazing! and I like the taste. Muscle Pharm's Combat 100% Whey mixes easily I never end up drinking chunks. I have tried all of the flavors and really love the Cappuccino, strawberry and chocolate. I am usually a vanilla over chocolate person, but I do not love their vanilla. The cookies and cream is pretty much vanilla with black chunks. But I love this protein no matter what and I definitely see myself using this for a very long time, make sure to try it out." },
            new Review { SupplementId = 1, Rating = 10, PublishDate = date.AddDays(-75), Content = "This protein is amazing! I have tried a lot of different protein powders and I have yet to find one that blends as well or tastes as good as this one. The Double Rich Chocolate and Mocha Cappuccino are perfect for anyone who does not like super sweet drinks. The double rich chocolate reminds me a lot of Ovaltine! Highly recommend." },
            new Review { SupplementId = 20, Rating = 10, PublishDate = date.AddDays(-90), Content = "I prefer aminos with a little something extra, be it a focus boost, energy kick, etc. This products has a good amino profile, as well as a bit of energy boost. It says it can be used as a preworkout, but I feel it'd be a very light one. I used it as an intra, and it was good for keeping my energy steady through my whole workout. As for the flavor, it was a bit too sweet for me, and while cotton candy isn't a favorite of mine, they did absolutely nail it which is why it got a 10." },
            new Review { SupplementId = 12, Rating = 8, PublishDate = date.AddDays(-105), Content = "I love this preworkout. It has the perfect amount of caffeine, beta alanine, and creatine for me. I only get the tingles if I drink it really fast, but you get used to it after awhile anyway. The flavors are awesome, and you can't beat the price when Bodybuilding does promos for it. Strawberry Lime isn't a flavor I would order again and my favorite so far is definitely watermelon!" },
            new Review { SupplementId = 4, Rating = 7, PublishDate = date.AddDays(-120), Content = "First experience with a fish oil and these do exactly what they are supposed to. Capsules are pretty big but they have a coating that makes swallowing them effortless. I gave the flavor a 10/10, however there really is not a flavor with these unless you are sucking on the capsule or something; when swallowed like a normal capsule I don't taste a thing. I keep reading other reviews that these give bad fish burps, but that is not the case with me. I take one in the morning with some vitamins + a meal, then one in the afternoon and no fishy burps." }
        };

        public static IEnumerable<Review> reviewsSecondPart = new List<Review>
        {
            new Review { SupplementId = 29, Rating = 10, PublishDate = date.AddDays(-135), Content = "This was the best multi vitamin I have ever taken. My energy was off the charts, my body felt good, and I was more mentally ready to go for my workouts while taking this. It is a great product and I'll definitely buy it again. " },
            new Review { SupplementId = 15, Rating = 6, PublishDate = date.AddDays(-150), Content = "I have used White Flood in the past and have come back to it again. It's a nice substitute Pre that I like to use if I am working out later in the day and don't want to stay up all night. It's simple and works well enough. I'll likely have some on hand in the case of those late night workouts in the future. Raspberry Lemonade is a pretty decent tasting Pre supplement, but the rave reviews of Bubble Gum are making me curious. I'll probably give that a shot next time when I need to reload." },
            new Review { SupplementId = 11, Rating = 8, PublishDate = date.AddDays(-165), Content = "I have tried a sample of this product from CL Sample pack promotion. After just trying it once, I end up ordering tons... 6 tubs from Buy 2 get 1 Free. Now that I have tried Green Mag, I shall never consume unflavored boring creatine! This stuff is delicious and dissolves completely in water unlike the normal Creapure sold by many. Normally I'm not a fan of Watermelon but this flavor was done just right for my tastes so I end up ordering 2x Watermelon and 4x Sour Green Apple (Just completely tasty). Aside from creatine mixing and tasting so good, it also has additional energy ingredients which helps fuel workouts or need to wake up a bit. I take Green Mag every morning, I feel more energized during the mornings and ready to train hard." },
            new Review { SupplementId = 22, Rating = 5, PublishDate = date.AddDays(-180), Content = "Alright, this is one of the best pre-workouts I've purchased. I've gone with some cheaper brands to cut costs a little, but keep coming back to NO Xplode. It's got a great blend of creatines It's got a great blend of creatine, aminos, and energy boosting ingredients, to include caffeine. It tastes great, and when you add additional BCAAs to the mix, it still tastes good. This gives me the pump I need for my workouts, and keeps me focused throughout my gym time. I'll keep coming back to this as long as they don’t jack the prices up. I like to try the different flavors so I don't get tired of one single flavor." },
            new Review { SupplementId = 8, Rating = 8,PublishDate = date.AddDays(-195), Content = "This product is amazing, but it is hard to mix well in the water. I'm taking 5 gm pure qualitine creatine each day from last 20 days and I can feel the amazing result. Now, I can lift heavy weight on strength exercises like deadlift, squats and bench press. I always go harder and harder with the help of this product and I can also feel the full energy level in the entire workout. I'll highly recommend this product to everyone, price is also good. Therefore, all things are best among all the products and you can trust on this product." },
            new Review { SupplementId = 28, Rating = 8, PublishDate = date.AddDays(-210), Content = "This is my favorite Pre Workout, i love it, it gives me energy, focus, without crash, jitter or anxious and also have the perfect combination of aminos, I usually see people here rating bad supplements, they don't consider its a supplement, you won't get big, huge or get massive pump all the time, indeed expect too much for a just supplement. Btw, so sad its not available anymore." },
            new Review { SupplementId = 16, Rating = 7, PublishDate = date.AddDays(-235), Content = "I have tried other recovery products with and without creatine. This has been one of the best for me and I keep coming back to it because it really reduces the soreness when you push a little harder or lift a little heavier. None of their flavours have that excessive, sickly sweet taste that comes from too much artificial sweetener. Every body is different and this is one that works very well for me." }
        };

        public static IEnumerable<Comment> comentsInSupplement = new List<Comment>
        {
            new Comment { PublishDate = date.AddDays(-15), Content = "It's definitely good for that cost!" },
            new Comment { PublishDate = date.AddDays(-30), Content = "I highly recommend this product!" },
            new Comment { PublishDate = date.AddDays(-54), Content = "This is my favourite product of this brand!" },
            new Comment { PublishDate = date.AddDays(-60), Content = "I'm not satisfied with the effect!" },
            new Comment { PublishDate = date.AddDays(-75), Content = "I would recommend this product to my friends!" },
            new Comment { PublishDate = date.AddDays(-90), Content = "I'm a little disappointed! I would not buy it again!" },
            new Comment { PublishDate = date.AddDays(-105), Content = "Not good enough for this price!" },
            new Comment { PublishDate = date.AddDays(-120), Content = "I really liked this product!" },
            new Comment { PublishDate = date.AddDays(-135), Content = "One of the best products I have ever tried!" },
            new Comment { PublishDate = date.AddDays(-150), Content = "It's great! I really love it!" },
            new Comment { PublishDate = date.AddDays(-165), Content = "One of my favourite products!" },
            new Comment { PublishDate = date.AddDays(-180), Content = "Quality product!" },
            new Comment { PublishDate = date.AddDays(-195), Content = "Good price for the amount of servings!" },
            new Comment { PublishDate = date.AddDays(-210), Content = "It's great! I really like it!" },
            new Comment { PublishDate = date.AddDays(-225), Content = "Well, it's fine! I works good!" }
        };

        public static IEnumerable<OrderSupplements> supplementsInOrderFirstPart = new List<OrderSupplements>
        {
            new OrderSupplements { SupplementId = 1, Quantity = 2, Price = 19.99m },
            new OrderSupplements { SupplementId = 3, Quantity = 5, Price = 29.99m },
            new OrderSupplements { SupplementId = 5, Quantity = 3, Price = 9.99m },
            new OrderSupplements { SupplementId = 10, Quantity = 1, Price = 59.99m },
            new OrderSupplements { SupplementId = 13, Quantity = 4, Price = 19.99m },
            new OrderSupplements { SupplementId = 15, Quantity = 1, Price = 39.99m },
        };

        public static IEnumerable<OrderSupplements> supplementsInOrderSecondPart = new List<OrderSupplements>
        {
            new OrderSupplements { SupplementId = 20, Quantity = 3, Price = 19.99m },
            new OrderSupplements { SupplementId = 12, Quantity = 1, Price = 59.99m },
            new OrderSupplements { SupplementId = 5, Quantity = 4, Price = 19.99m },
            new OrderSupplements { SupplementId = 29, Quantity = 1, Price = 39.99m },
        };

        public static IEnumerable<OrderSupplements> supplementsInOrderThirdPart = new List<OrderSupplements>
        {
            new OrderSupplements { SupplementId = 14, Quantity = 2, Price = 19.99m },
            new OrderSupplements { SupplementId = 18, Quantity = 5, Price = 29.99m },
            new OrderSupplements { SupplementId = 8, Quantity = 3, Price = 59.99m },
        };

        public static IEnumerable<OrderSupplements> supplementsInOrderFourthPart = new List<OrderSupplements>
        {
            new OrderSupplements { SupplementId = 13, Quantity = 2, Price = 19.99m },
            new OrderSupplements { SupplementId = 20, Quantity = 5, Price = 29.99m },
            new OrderSupplements { SupplementId = 25, Quantity = 1, Price = 9.99m },
            new OrderSupplements { SupplementId = 9, Quantity = 1, Price = 59.99m },
            new OrderSupplements { SupplementId = 5, Quantity = 3, Price = 19.99m },
            new OrderSupplements { SupplementId = 2, Quantity = 2, Price = 9.99m },
            new OrderSupplements { SupplementId = 22, Quantity = 1, Price = 39.99m },
        };

        public static IEnumerable<OrderSupplements> supplementsInOrderFifthPart = new List<OrderSupplements>
        {
            new OrderSupplements { SupplementId = 19, Quantity = 2, Price = 19.99m },
            new OrderSupplements { SupplementId = 14, Quantity = 5, Price = 29.99m },
            new OrderSupplements { SupplementId = 18, Quantity = 2, Price = 59.99m },
            new OrderSupplements { SupplementId = 5, Quantity = 4, Price = 19.99m },
            new OrderSupplements { SupplementId = 3, Quantity = 1, Price = 39.99m },
        };

        public static IEnumerable<OrderSupplements> supplementsInOrderSixPart = new List<OrderSupplements>
        {
            new OrderSupplements { SupplementId = 4, Quantity = 2, Price = 19.99m },
            new OrderSupplements { SupplementId = 8, Quantity = 5, Price = 9.99m },
            new OrderSupplements { SupplementId = 16, Quantity = 3, Price = 9.99m },
            new OrderSupplements { SupplementId = 24, Quantity = 1, Price = 59.99m },
            new OrderSupplements { SupplementId = 28, Quantity = 4, Price = 19.99m },
            new OrderSupplements { SupplementId = 30, Quantity = 1, Price = 39.99m },
        };
    }
}