namespace FitStore.Web.Infrastructure
{
    using Common.Extensions;
    using Data.Models;
    using System;
    using System.Collections.Generic;

    public class SeedConstants
    {
        private static DateTime bestBeforeDate = DateTime.UtcNow.AddYears(1);

        public const string Protein = "Protein";
        public const string AminoAcids = "Amino Acids";
        public const string Creatine = "Creatine";
        public const string Vitamins = "Vitamins";

        public const string Whey = "Whey";
        public const string Gainer = "Gainer";
        public const string Isolate = "Isolate";
        public const string Bcaa = "BCAA";
        public const string Glutamine = "Glutamine";
        public const string PreWorkouts = "Pre Workouts";
        public const string Monohydrate = "Monohydrate";
        public const string Matrix = "Matrix";
        public const string Multivitamins = "Multivitamins";
        public const string FishOil = "Fish Oil";

        public const int WheyId = 1;
        public const int GainerId = 2;
        public const int IsolateId = 3;
        public const int BcaaId = 4;
        public const int GlutamineId = 5;
        public const int PreWorkoutsId = 6;
        public const int MonohydrateId = 7;
        public const int MatrixId = 8;
        public const int MultivitaminsId = 9;
        public const int FishOilId = 10;

        public const string OptimumNutrition = "Optimum Nutrition";
        public const string ControlledLabs = "Controlled Labs";
        public const string MusclePharm = "Muscle Pharm";
        public const string BulkPowders = "Bulk Powders";
        public const string Gaspari = "Gaspari";
        public const string Bsn = "BSN";

        public const int OptimumNutritionId = 1;
        public const int ControlledLabsId = 2;
        public const int MusclePharmId = 3;
        public const int BulkPowdersId = 4;
        public const int GaspariId = 5;
        public const int BsnId = 6;

        public const string OptimumNutritionAddress = "USA, Florida, Miami";
        public const string ControlledLabsAddress = "USA, Texas, Houston";
        public const string MusclePharmAddress = "USA, California, Los Angeles";
        public const string BulkPowdersAddress = "USA, Caifornia, San Francisko";
        public const string GaspariAddress = "USA, Colorado, Denver";
        public const string BsnAddress = "USA, Nevada, Las vegas";

        public static IEnumerable<Supplement> proteinSupplements = new List<Supplement>
        {
            new Supplement { SubcategoryId = WheyId, ManufacturerId = OptimumNutritionId, Name = "Gold Standard 100% Whey", Description ="True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 8, Price = 99.99m },
            new Supplement { SubcategoryId = WheyId, ManufacturerId = GaspariId, Name = "MyoFusion Advanced", Description = "Myofusion Advanced Protein’s formula provides the most up to date and scientifically proven blend of protein available. Featuring a synergistic mix of immediate, fast acting, and time released forms of whey & casein, Myofusion is able to provide the body with muscle fortifying amino acids all day long. Available in delicious flavors like Peanut Butter Cookie, Cookies & Cream, and creamy Milk Chocolate, Myofusion is the perfect solution for any athlete looking to improve their performance and physique!", Quantity = 10, Price = 44.99m },
            new Supplement { SubcategoryId = WheyId, ManufacturerId = MusclePharmId, Name = "Combat 100% Whey", Description = "Combat 100% WHEY is a low-carb, high-protein, great-tasting protein supplement with minimal fat and low sodium that delivers fast digesting protein sources to build and maintain lean muscle mass. Combat 100% Whey combines two of the fastest digesting, most efficient, and cleanest protein sources available: Whey Protein Isolate and Whey protein Concentrate. Whey protein has the highest bioavailability among complete proteins (protein that contains a complete amino acid profile of all 9 essential amino acids) and also has the highest absorption rate among any other proteins.", Quantity = 0, Price = 54.99m },
            new Supplement { SubcategoryId = GaspariId, ManufacturerId = BsnId, Name = "BSN Syntha 6", Description = "Syntha 6 is an ultra-premium protein powder with 22g protein per serving and is BSN's best-tasting protein on the market. Syntha 6 not only includes essential amino acids and essential fatty acids, but is also an excellent source of fiber, which makes it a nutritious and multi-functional protein supplement. Syntha 6 is the go-to protein for any nutrition or exercise regimen because it is designed to suit a variety of active lifestyles and diet plans. And with Syntha 6, the high standard of quality protein comes with taste to match, thanks to BSN's exclusive flavor technology.", Quantity = 6, Price = 89.99m},
            new Supplement { SubcategoryId = GaspariId, ManufacturerId = BulkPowdersId, Name = "Complete Mass", Description = "Complete Mass is a calorie dense weight gainer, designed for real hard gainers. Not only does Complete Mass contain over 500kcal per serving, but it is crammed with multiple sources of protein and is fortified with amino acids such as leucine. In addition, Complete Mass tastes so good that you'll look forward to each and every shake.", Quantity = 0, Price = 64.99m },
            new Supplement { SubcategoryId = IsolateId, ManufacturerId = OptimumNutritionId, Name = "Gold Standard 100% Isolate", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 4, Price = 74.99m},
        };

        public static IEnumerable<Supplement> aminoAcidsSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = BsnId, Name = "Amino X", Description = "Amino X is a stimulant-free, BCAA formula designed to support endurance during your workout and aid in muscle recovery post training, so you can push your performance to the next level. Featuring a 10 gram blend of BCAAs and the essential amino acids, L-Alanine, Taurine and L-Citrulline, Amino X will help your body recover from today’s workout and prepare for tomorrow’s.", Quantity = 8, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = GaspariId, Name = "BCAA 6000", Description = "BCAA 6000 from Gaspari Nutrition uses a leucine heavy, 4:1:1 ratio of 100% pure branched chain amino acids in a formula that provides clinically validated and effective quantities of these critical nutrients in every dose. The addition of an advanced, highly bio-available form of Vitamin B-6 to the BCAA 6000 complex, will also help to enhance your energy and endurance levels, helping to further maximize your training while simultaneously enhancing recovery.", Quantity = 0, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = ControlledLabsId, Name = "Purple Wraath", Description = "The Purple Wraath PurplEAA Complex is a very efficient formula based on the science of actual homo sapiens muscle protein and clinical studies on human amino acid assimilation. Essential Amino Acids (EAA's) are the building blocks of lean muscle mass, but the EAA's from whey protein can take hours to enter circulation.", Quantity = 6, Price = 54.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = BcaaId, ManufacturerId = OptimumNutritionId, Name = "BCAA 1000", Description = "BCAA 1000 contains a balance of Branched Chain Amino Acids, which are building blocks of muscle mass and size. Metabolized directly in the muscle, BCAAs may improve nitrogen retention by sparing other amino acid groups for repair and rebuilding. The Branched Chain Amino Acids (BCAAs), so named because of their unique branched chemical structure, are essential in that the body cannot make them from other compounds. In recent times, these amino acids have been investigated for their potential anticatabolic (reducing muscle breakdown) and anabolic (muscle building) effects.", Quantity = 2, Price = 14.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = GlutamineId, ManufacturerId = OptimumNutritionId, Name = "Glutamine Powder", Description = "Glutamine is the most abundant amino acid in the body, comprising more than 60% of the free amino acid pool in skeletal muscle and greater than 20% of total circulating amino acids. Supplemental L-Glutamine may help reduce muscle soreness and rebuild muscle tissue.", Quantity = 4, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = GlutamineId, ManufacturerId = GaspariId, Name = "Pure L-Glutamine", Description = "Utilizing only ultra-pure L-Glutamine with no synthetic colors or fillers, Gaspari Nutrition's glutamine is your solution in amino acid support. Whether you are strength training or pushing yourself through long aerobic training sessions, glutamine can help support one of your body's most abundant amino acids. Gaspari Nutrition's L-Glutamine offers you a high value product at a rock bottom price. You can rest assured this product is made with only the highest quality in mind. Be sure when taking glutamine to drink at least 8 glasses of water daily for optimal results in strength and conditioning training.", Quantity = 0, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = BsnId, Name = "Cell Mass 2.0", Description = "CellMass 2.0 is a concentrated post-workout recovery agent that helps promote recovery, endurance, strength and overall performance. When taken as directed, CellMass 2.0's formula delivers 5g of creatine, 3g of glutamine and glutamic acid, and 10g of amino acids per day, along with taurine and hydrolyzed whey protein, all designed to help kick-start the recovery process after a workout.", Quantity = 6, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = GaspariId, Name = "Super Pump MAX", Description = "Are you ready to take your workouts to the MAX? If so, the only way to get there is through the use of clinically researched and validated ingredients at their proven doses. Super Pump MAX is a one of a kind breakthrough in pre-workout supplementation that offers the most effective compounds available for intense energy and focus, mind blowing pumps, and muscle anabolism.", Quantity = 6, Price = 34.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = ControlledLabsId, Name = "White Flood", Description = "Now called White Flood Classic, it is a tried and true preworkout formula that will rev you up for lifting and cardio like none other. Not only will you experience out of this world pumps, but tons of extra energy and true muscle building potential. That muscle building potential comes from the addition of compounds usually not seen in preworkout formulas of the past. We have also included anti-oxidants to scavenge any free radicals normally elicited by Nitric Oxide inducing ingredients during exercise.", Quantity = 6, Price = 29.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = MusclePharmId, Name = "Natural Series Pre-Workout", Description = "Muscle Pharm Pre-Workout is a combination of organic caffeine, natural botanicals, electrolytes, and amino acids that work together to support your training goals and bring you pure, unadulterated results. We brought together a team of athletes, scientists and naturalists who believe that an authentic, results-focused supplement can also be clean, pure and nutritive.", Quantity = 0, Price = 39.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = PreWorkoutsId, ManufacturerId = OptimumNutritionId, Name = "Gold Standard Pre-Workout", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 4, Price = 29.99m },
        };

        public static IEnumerable<Supplement> creatineSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MatrixId, ManufacturerId = ControlledLabsId, Name = "Green Magnitude", Description = "We have responded to customer demand and the result: Green MAGnitude... Creatine with attitude. If you want to increase your stamina in the gym and gain size and strength, Green MAGnitude is the right choice for you. If you want similar results in convenient capsule form, we recommend Green Bulge. Either way, you are getting a full dose of patented Magnesium Creatine Chelate that has been clinically surmised to increase strength. Green MAGnitude is our most advanced powder creatine matrix and one of the first creatine products on the market to combine Magnesium Creatine Chelate (a patented form of creatine), with Dicreatine Malate (creatine bound with Malic Acid) to deliver synergistic benefits you can actually feel working during your workout.", Quantity = 8, Price = 39.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MonohydrateId, ManufacturerId = OptimumNutritionId, Name = "Micronized Creatine Powder", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 0, Price = 19.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MonohydrateId, ManufacturerId = GaspariId, Name = "Qualitine", Description = "Gaspari Nutrition features Qualitin, a premium brand of creatine guaranteed to be the highest in quality, purity and safety. Gaspari Nutrition uses only 99.9% pure creatine monohydrate that has been micronized to insure instant dissolution into water and other suitable liquids. Qualitine is tasteless, odorless, crystalline and pure-qualities that are obvious from the moment you open the bottle and every time you use this elite product. Creatine monohydrate is perhaps the most studied dietary supplement in the Sports Nutrition industry.", Quantity = 4, Price = 14.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MonohydrateId, ManufacturerId = BulkPowdersId, Name = "Bulk Powders Creatine", Description = "Bulk Powders Creatine Monohydrate is a high quality, ultra-pure form of Creatine Monohydrate. Not only this, but Bulk Powders Creatine Monohydrate offers incredible value for money. Many Creatine Monohydrate products have been shown to contain up to 5% impurities, whereas Bulk Powders Creatine Monohydrate is 99.9% pure. We display the latest Certificate of Analysis on this page(under the product image) as evidence of our commitment to product quality.", Quantity = 6, Price = 24.99m },
        };

        public static IEnumerable<Supplement> vitaminsSupplements = new List<Supplement>
        {
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = BulkPowdersId, Name = "Omega 3 Fish Oil", Description = "Bulk Powders Omega 3 Fish Oil Softgels contains 180mg EPA and 120mg DHA per softgel – this is far higher than many fish oil products. If you’re looking for even higher levels of EPA and DHA, then take a look at our popular Super Strength Fish Oils 1000mg. Omega 3 Fish Oil Softgels deliver EPA and DHA in a cost effective format.", Quantity = 6, Price = 4.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = OptimumNutritionId, Name = "Fish Oil Softgels", Description = "True Strength is a journey. It never rests, it never quits. It's about overcoming obstacles, accomplishing goals, and recognizing achievements. And then it resets to achieve again. As your trusted sports nutrition partner in goal achievement, ON demonstrates that same passion while crafting our products. From the raw materials we source to our state-of-the-art manufacturing processes, no compromises are made. You set the bar higher after every workout, we set the bar higher to redefine the industry standards and ensure you realize optimum results.", Quantity = 2, Price = 9.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = ControlledLabsId, Name = "Orange OxiMega Fish Oil", Description = "Many people don’t realize the crucial effects that overall health supplements can play on their training. Without the essential nutrients your body needs to survive and flourish, it cannot build a strong foundation that is so crucial to lean mass gains. Orange OxiMega was designed to help you establish a strong, healthful, foundation on which to base your training, diet and supplementation. Coupled together with Orange Triad, Super Fish Oil Formulas will have all of your overall health requirements exceeded including omegas, vitamins, minerals, fruit, vegetables, digestive support, immune support, joint support, and cardiovascular support.", Quantity = 8, Price = 19.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = FishOilId, ManufacturerId = MusclePharmId, Name = "Fish Oil Muscle Pharm", Description = "This essential fatty acid facilitates an overall decrease in fat and cholesterol consumption from your omega intake. Not only are these Nordic fish oil softgels a nutritional masterpiece, they are also enteric coated and citrus flavored so you won't experience the regurgitation (which are called fish oil burps) that people associate with cheaper, cruder formulations. Our Nordic fish oil's molecular integrity is protected so you can be assured of the utmost quality.", Quantity = 4, Price = 14.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MultivitaminsId, ManufacturerId = OptimumNutritionId, Name = "Opti-Men", Description = "Optimum Nutrition's Opti-Men is a complete Nutrient Optimization System providing 70+ active ingredients in 4 blends specifically designed to support the nutrient needs of active men. Taken as a single tablet at breakfast, lunch and dinner, our new & improved multi provides 22 vitamins and essential minerals - including 1,500 IU of Vitamin D, free form amino acids, botanical extracts and antioxidants in foundational amounts that can be built upon through consumption of a healthy balanced diet. Think of Opti-Men as potent nutritional insurance for your fitness lifestyle.", Quantity = 8, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MultivitaminsId, ManufacturerId = OptimumNutritionId, Name = "Opti-Women", Description = "Vitamins, minerals and other essential nutrients are the body's fundamental building blocks. Among other things, they contribute to our energy levels, immunity, performance and overall vitality. Opti-Women has been designed as a comprehensive Nutrient Optimization System complete with botanicals, antioxidants, and other gender-focused components. By packing 40 active ingredients into one pill, much more than a multi has been created.", Quantity = 8, Price = 24.99m },
            new Supplement { BestBeforeDate = bestBeforeDate, Picture = "wwwroot/images/supplements/amino-x.jpg".ToByteArray(), SubcategoryId = MultivitaminsId, ManufacturerId = ControlledLabsId, Name = "Orange Triad", Description = "Designed for the serious athlete, Orange Triad delivers! Serious athletes are unique in that they intentionally subject their bodies to incredible amounts of stress with training and cardio. Over time, muscles, tendons, and ligaments take longer to recover which means you can't train them as often as you would like. Nutritional support is key to getting optimal results from your training. Orange Triad combines key vitamins, minerals, and nutrients for supporting optimal digestion, immune system, and joint health into one twice daily dietary supplement. The Joint and Flex Complexes help lubricate joints and cartilage as well as increase the resiliency of connective tissue, while the Digestion and Immune Complex includes digestive aids, and nutrient partitioning agents to take your performance to the next level.", Quantity = 10, Price = 29.99m }
        };
    }
}